### ISSUE TITLE
Resume Training

### ISSUE THREAD

**Issue by harshvb20** [ali-vilab/ACE_plus#26]
How to resume training from the saved checkpoints.?

**Comment by yuhodots** [comment]
I think you can use `CACHE_PRETRAIN_MODEL` or `PRETRAINED_MODEL` key in the config file. (e.g., train_config/ace_plus_lora.yaml)

For lora checkpoints, you can use `COMFYUI_LORA_MODEL`, `SWIFT_LORA_MODEL`, or `DIFFUSERS_LORA_MODEL`. I referred `modules/flux.py` file.

https://github.com/modelscope/scepter/blob/467652bd696738f70e952f3663ba3f7796720315/scepter/modules/model/backbone/flux/flux.py#L105-L107

Here is a example config:

```yaml
    DIFFUSION_MODEL:
      NAME: FluxMRACEPlus
      PRETRAINED_MODEL: ${FLUX_FILL_PATH}/flux1-fill-dev.safetensors
      ...
      DEPTH_SINGLE_BLOCKS: 38
      ATTN_BACKEND: flash_attn

      CACHE_PRETRAIN_MODEL: {MY CACHED PRETRAINED MODEL.safetensors}
      COMFYUI_LORA_MODEL: {MY CACHED LORA CHECKPOINTS.safetensors} 

```
